<?php
/**
 * Shared navigation tail — desktop + mobile nav after PRODUCTS dropdown.
 * Set $navActive before including: home|products|about|customer-stories|blog|contact
 */
$navActive = $navActive ?? '';

function nav_is_active(string $key): string
{
    global $navActive;
    return $navActive === $key ? ' w--current' : '';
}

function nav_aria_current(string $key): string
{
    global $navActive;
    return $navActive === $key ? ' aria-current="page"' : '';
}

$w = 'w-variant-23049969-09ac-2789-520b-3c6ae895bbc6';
$dl = 'nav_dropdown_link ' . $w . ' w-inline-block';
?>
</div></li>
<li class="nav_links_item <?= $w ?>"><div data-delay="400" data-hover="true" class="nav_dropdown_component <?= $w ?> w-dropdown"><div data-state="expanded" class="nav_links_link <?= $w ?> w-dropdown-toggle" id="w-dropdown-toggle-2" aria-controls="w-dropdown-list-2" aria-haspopup="menu" aria-expanded="false" role="button" tabindex="0"><a href="/customer-stories/" class="w-inline-block"><div class="nav_links_text u-text-style-small">Resources</div></a><div class="nav_links_svg"><svg data-wf--icon-arrow--direction="bottom" viewBox="0 0 66 70" fill="none" width="100%" height="100%" aria-hidden="true" class="u-svg w-variant-caa8b8e9-e8ec-6eb3-4526-30f19f7326f5"><path d="M17 2L50 34.9999L17 68" class="u-path"></path></svg></div></div><nav class="nav_dropdown_mega_wrap <?= $w ?> w-dropdown-list" id="w-dropdown-list-2" aria-labelledby="w-dropdown-toggle-2"><div class="nav_dropdown_mega_content <?= $w ?>"><div data-lenis-prevent="" class="nav_dropdown_mega_scroll"><div class="nav_dropdown_mega_contain <?= $w ?>"><div class="nav_dropdown_mega_layout <?= $w ?>"><ul role="list" class="nav_dropdown_list"><li class="nav_dropdown_item"><a href="/customer-stories/" class="<?= $dl ?><?= nav_is_active('customer-stories') ?>"<?= nav_aria_current('customer-stories') ?> tabindex="0"><div class="nav_links_text u-text-style-small">Customer Stories</div></a></li><li class="nav_dropdown_item"><a href="/blog/" class="<?= $dl ?><?= nav_is_active('blog') ?>"<?= nav_aria_current('blog') ?> tabindex="0"><div class="nav_links_text u-text-style-small">Blog</div></a></li></ul></div></div></div></div></nav></div></li>
</ul>
<ul role="list" class="nav_actions_wrap <?= $w ?> w-list-unstyled">
<li class="nav_buttons_item is-main <?= $w ?>"><div data-wf--button-main--variant="secondary" class="button_main_wrap" data-button=" " data-trigger="hover focus"><div class="clickable_wrap u-cover-absolute"><a target="" href="/about/" class="clickable_link w-inline-block<?= nav_is_active('about') ?>"<?= nav_aria_current('about') ?>><span class="clickable_text u-sr-only">About</span></a><button type="button" class="clickable_btn"><span class="clickable_text u-sr-only">About</span></button></div><div class="button_main_element w-variant-e85564cd-af30-a478-692b-71732aefb3ab"><svg xmlns="http://www.w3.org/2000/svg" width="100%" viewBox="0 0 12 16" fill="none" class="video-play"><path d="M11.25 7.79443L2.19575e-07 15.5887L9.00968e-07 0.000204548L11.25 7.79443Z" fill="black"></path></svg><div aria-hidden="true" class="button_main_text u-text-style-small">About</div><div class="button_main_icon u-hide-if-empty"></div></div></div></li>
<li class="nav_buttons_item"><div class="button_main_wrap" data-button=" " data-trigger="none"><div class="clickable_wrap u-cover-absolute"><a target="" href="/contact/" class="clickable_link w-inline-block<?= nav_is_active('contact') ?>"<?= nav_aria_current('contact') ?>><span class="clickable_text u-sr-only">Contact</span></a><button type="button" class="clickable_btn"><span class="clickable_text u-sr-only">Contact</span></button></div><div class="button_main_element"><svg xmlns="http://www.w3.org/2000/svg" width="100%" viewBox="0 0 12 16" fill="none" class="video-play"><path d="M11.25 7.79443L2.19575e-07 15.5887L9.00968e-07 0.000204548L11.25 7.79443Z" fill="black"></path></svg><div aria-hidden="true" class="button_main_text u-text-style-small">Contact</div><div class="button_main_icon u-hide-if-empty"></div></div></div></li>
</ul></nav></div></div></header>
<div data-animation="default" data-collapse="all" data-duration="400" data-easing="ease" data-easing2="ease" role="banner" class="nav_mobile_wrap w-nav"><div class="nav_mobile_contain"><div class="nav_mobile_layout"><a aria-label="Home Page" href="/" class="nav_mobile_logo w-inline-block<?= nav_is_active('home') ?>"<?= nav_aria_current('home') ?>><img src="/assets/images/royal-logo.webp" alt="Royal Associates Insurance Brokers" class="logo-svg"></a>
<nav role="navigation" class="nav_mobile_menu_wrap w-nav-menu"><div data-lenis-prevent="" class="nav_mobile_menu_scroll"><nav aria-label="Main" data-wf--menu--variant="mobile" class="nav_links_component"><ul role="list" class="nav_links_wrap w-list-unstyled">
<li class="nav_links_item"><div class="nav_links_link"><div role="listitem" class="footer_group_item"><a href="/" class="footer_link_wrap w-inline-block<?= nav_is_active('home') ?>"<?= nav_aria_current('home') ?>><div class="nav_links_text u-text-style-small">Home</div></a></div></div></li>
<li class="nav_links_item"><div data-delay="400" data-hover="true" class="nav_dropdown_component w-dropdown"><div data-state="expanded" class="nav_links_link w-dropdown-toggle" id="w-dropdown-toggle-3" aria-controls="w-dropdown-list-3" aria-haspopup="menu" aria-expanded="false" role="button" tabindex="0"><a href="/products/" class="w-inline-block<?= nav_is_active('products') ?>"<?= nav_aria_current('products') ?>><div class="nav_links_text u-text-style-small">PRODUCTS</div></a><div class="nav_links_svg"><svg data-wf--icon-arrow--direction="bottom" viewBox="0 0 66 70" fill="none" width="100%" height="100%" aria-hidden="true" class="u-svg w-variant-caa8b8e9-e8ec-6eb3-4526-30f19f7326f5"><path d="M17 2L50 34.9999L17 68" class="u-path"></path></svg></div></div><nav class="nav_dropdown_mega_wrap w-dropdown-list" id="w-dropdown-list-3" aria-labelledby="w-dropdown-toggle-3"><div class="nav_dropdown_mega_content"><div data-lenis-prevent="" class="nav_dropdown_mega_scroll"><div class="nav_dropdown_mega_contain"><div class="nav_dropdown_mega_layout"><ul role="list" class="nav_dropdown_list"><li class="nav_dropdown_item"><a href="/products/" class="nav_dropdown_link w-inline-block<?= nav_is_active('products') ?>"<?= nav_aria_current('products') ?> tabindex="0"><div class="nav_links_text u-text-style-small">Overview</div></a></li><li class="nav_dropdown_item"><a href="/products#corporate" class="nav_dropdown_link w-inline-block" tabindex="0"><div class="nav_links_text u-text-style-small">Corporate Insurance</div></a></li><li class="nav_dropdown_item"><a href="/products#individual" class="nav_dropdown_link w-inline-block" tabindex="0"><div class="nav_links_text u-text-style-small">Individual Insurance</div></a></li></ul></div></div></div></div></nav></div></li>
<li class="nav_links_item"><div data-delay="400" data-hover="true" class="nav_dropdown_component w-dropdown"><div data-state="expanded" class="nav_links_link w-dropdown-toggle" id="w-dropdown-toggle-5" aria-controls="w-dropdown-list-5" aria-haspopup="menu" aria-expanded="false" role="button" tabindex="0"><a href="/customer-stories/" class="w-inline-block"><div class="nav_links_text u-text-style-small">Resources</div></a><div class="nav_links_svg"><svg data-wf--icon-arrow--direction="bottom" viewBox="0 0 66 70" fill="none" width="100%" height="100%" aria-hidden="true" class="u-svg w-variant-caa8b8e9-e8ec-6eb3-4526-30f19f7326f5"><path d="M17 2L50 34.9999L17 68" class="u-path"></path></svg></div></div><nav class="nav_dropdown_mega_wrap w-dropdown-list" id="w-dropdown-list-5" aria-labelledby="w-dropdown-toggle-5"><div class="nav_dropdown_mega_content"><div data-lenis-prevent="" class="nav_dropdown_mega_scroll"><div class="nav_dropdown_mega_contain"><div class="nav_dropdown_mega_layout"><ul role="list" class="nav_dropdown_list"><li class="nav_dropdown_item"><a href="/customer-stories/" class="nav_dropdown_link w-inline-block<?= nav_is_active('customer-stories') ?>"<?= nav_aria_current('customer-stories') ?> tabindex="0"><div class="nav_links_text u-text-style-small">Customer Stories</div></a></li><li class="nav_dropdown_item"><a href="/blog/" class="nav_dropdown_link w-inline-block<?= nav_is_active('blog') ?>"<?= nav_aria_current('blog') ?> tabindex="0"><div class="nav_links_text u-text-style-small">Blog</div></a></li></ul></div></div></div></div></nav></div></li>
</ul>
<ul role="list" class="nav_actions_wrap w-list-unstyled"><li class="nav_buttons_item is-main"><div data-wf--button-main--variant="secondary" class="button_main_wrap" data-button=" " data-trigger="hover focus"><div class="clickable_wrap u-cover-absolute"><a target="" href="/about/" class="clickable_link w-inline-block<?= nav_is_active('about') ?>"<?= nav_aria_current('about') ?>><span class="clickable_text u-sr-only">About</span></a><button type="button" class="clickable_btn"><span class="clickable_text u-sr-only">About</span></button></div><div class="button_main_element w-variant-e85564cd-af30-a478-692b-71732aefb3ab"><svg xmlns="http://www.w3.org/2000/svg" width="100%" viewBox="0 0 12 16" fill="none" class="video-play"><path d="M11.25 7.79443L2.19575e-07 15.5887L9.00968e-07 0.000204548L11.25 7.79443Z" fill="black"></path></svg><div aria-hidden="true" class="button_main_text u-text-style-small">About</div><div class="button_main_icon u-hide-if-empty"></div></div></div></li><li class="nav_buttons_item"><div data-wf--button-main--variant="primary" class="button_main_wrap" data-button=" " data-trigger="hover focus"><div class="clickable_wrap u-cover-absolute"><a target="" href="/contact/" class="clickable_link w-inline-block<?= nav_is_active('contact') ?>"<?= nav_aria_current('contact') ?>><span class="clickable_text u-sr-only">Contact</span></a><button type="button" class="clickable_btn"><span class="clickable_text u-sr-only">Contact</span></button></div><div class="button_main_element"><svg xmlns="http://www.w3.org/2000/svg" width="100%" viewBox="0 0 12 16" fill="none" class="video-play"><path d="M11.25 7.79443L2.19575e-07 15.5887L9.00968e-07 0.000204548L11.25 7.79443Z" fill="black"></path></svg><div aria-hidden="true" class="button_main_text u-text-style-small">Contact</div><div class="button_main_icon u-hide-if-empty"></div></div></div></li></ul></nav></div></nav><div data-state="open" class="nav_button_wrap w-nav-button" style="-webkit-user-select: text;" aria-label="menu" role="button" tabindex="0" aria-controls="w-nav-overlay-0" aria-haspopup="menu" aria-expanded="false"><div class="nav_button_layout"><div class="nav_button_line is-1"></div><div class="nav_button_line is-2"></div></div></div></div></div><div class="w-nav-overlay" data-wf-ignore="" id="w-nav-overlay-0"></div></div><div class="nav_menu_backdrop"></div><div class="u-embed-js w-embed w-script"><script>
document.addEventListener("DOMContentLoaded", function () {
  document.querySelectorAll(".nav_skip_wrap").forEach(function (link) {
    const target = document.querySelector("main");
    if (!target) return;
    link.addEventListener("click", function () {
      target.setAttribute("tabindex", "-1");
      target.focus();
    });
  });
});
</script></div></div>
