<?php
return [
  'individual' => [
    1 => [
      'name' => 'Retail Products',
      'short' => 'Liability coverage for retail sellers against claims from product sales.',
      'desc' => 'Royal Associates offers Retail Products Liability Insurance, which provides coverage for retail sellers against liability for losses or injuries suffered as a result of purchasing a product from a buyer, user, or bystander. This insurance protects retail businesses against claims arising from the sale of goods, products, medicines, or foods sold to the public. It provides financial protection in case of lawsuits or claims related to product defects, injuries, or damages caused by the products sold.',
      'img' => '01_Retail_Products.png',
    ],
    2 => [
      'name' => 'Healthcare Insurance',
      'short' => 'Comprehensive medical expense coverage for individuals and groups.',
      'desc' => 'Royal Associates provides comprehensive Healthcare Insurance plans that cover the risk of medical expenses for individuals or groups. This insurance spreads the risk over numerous policyholders and helps protect against the high costs of medical treatments, hospitalization, surgeries, and other healthcare services. It ensures that policyholders have access to quality healthcare without incurring significant financial burdens.',
      'img' => '02_Healthcare_Insurance.png',
    ],
    3 => [
      'name' => 'International / Offshore Healthcare',
      'short' => 'Medical coverage for individuals and organizations operating overseas.',
      'desc' => 'For individuals or organizations operating internationally or in offshore locations, Royal Associates offers International/Offshore Healthcare Insurance. This specialized insurance provides coverage for medical expenses and emergency medical services in foreign countries. It ensures that policyholders have access to healthcare services and facilities wherever they are located globally, providing peace of mind and financial protection.',
      'img' => '03_International_Offshore_Healthcare_Insurance.png',
    ],
    13 => [
      'name' => 'Personal Accident',
      'short' => 'Financial support for bodily injuries from accidents.',
      'desc' => 'Personal Accident Insurance offered by Royal Associates provides financial support in the event of a serious accident, injury, or fatal accident. This insurance covers bodily injuries caused solely by external, violent, and accidental means. It offers financial compensation to policyholders or their beneficiaries, helping them cope with medical expenses, disability-related costs, loss of income, and other financial burdens resulting from an accident.',
      'img' => '13_Personal_Accident.png',
    ],
    15 => [
      'name' => 'Sports and Travel Insurance',
      'short' => 'Coverage for sports activities and domestic/international travel.',
      'desc' => 'Royal Associates provides Sports and Travel Insurance, which covers individuals participating in sports activities and traveling domestically and internationally. This insurance includes coverage for emergency medical expenses, trip cancellation or interruption, personal accident, personal liability, baggage loss or delay, and other travel-related risks. It ensures that individuals have financial protection and assistance during their sports activities or trips, no matter where they are in the world.',
      'img' => '15_Sports_and_Travel_Insurance.png',
    ],
    17 => [
      'name' => 'Homeowners Insurance',
      'short' => 'Coverage for private residences, property, and liability.',
      'desc' => 'Homeowners Insurance provided by Royal Associates offers comprehensive coverage for private residences. This insurance protects homeowners by providing property protection, liability coverage, and financial reimbursement for damage or theft of their homes and belongings. It also includes coverage for additional living expenses in case of temporary displacement due to covered events.',
      'img' => '17_Homeowners_Insurance.png',
    ],
    18 => [
      'name' => 'Motor Risks Insurance',
      'short' => 'Coverage for vehicles against accidents, theft, fire, and liability.',
      'desc' => 'Motor Risks Insurance provided by Royal Associates covers vehicles against various risks, including accidents, theft, fire, and third-party liability. This insurance offers financial protection for vehicle owners and helps cover expenses related to repairs, replacements, and legal liabilities arising from accidents or damages involving insured vehicles.',
      'img' => '18_Motor_Risks_Insurance.png',
    ],
    29 => [
      'name' => 'Individual and Group Life Insurance',
      'short' => 'Life coverage providing financial protection to individuals and families.',
      'desc' => 'Royal Associates offers Individual and Group Life Insurance policies that provide financial protection and support to individuals and their families. Individual Life Insurance offers coverage for an individual\'s life, providing benefits to beneficiaries in the event of the insured person\'s death. Group Life Insurance provides coverage for a group of individuals, typically offered by employers as part of employee benefits packages.',
      'img' => '29_Individual_and_Group_Life_Insurance.png',
    ],
    30 => [
      'name' => 'Pension Schemes',
      'short' => 'Retirement savings plans for a secure financial future.',
      'desc' => 'Pension Schemes provided by Royal Associates are retirement savings plans designed to help individuals accumulate funds for their retirement years. These schemes offer various options for individuals to contribute and invest their savings, ensuring a reliable source of income after retirement. Royal Associates provides advice and administration services for pension schemes, helping individuals plan for a secure financial future.',
      'img' => '30_Pension_Schemes.png',
    ],
  ],
  'corporate' => [
    4 => [
      'name' => 'Bankers Blanket Bond',
      'short' => 'Fidelity bond protecting banks from employee dishonesty and fraud.',
      'desc' => 'Bankers Blanket Bond (BBB) is a fidelity bond purchased from an insurance broker to protect banks against losses resulting from various criminal acts carried out by employees. Royal Associates offers this insurance coverage, which safeguards banks from risks such as employee dishonesty, fraud, forgery, theft, and other related crimes. BBB is often a requirement for banks to operate legally, and Royal Associates ensures banks have the necessary coverage to mitigate these risks.',
      'img' => '04_Bankers_Blanket_Bond.png',
    ],
    5 => [
      'name' => 'Contractors All Risks Insurance',
      'short' => 'Protection for contractors against property damage and third-party claims.',
      'desc' => 'Contractors All Risks Insurance is a specialized policy provided by Royal Associates to protect contractors and construction companies against property damage and third-party injury or damage claims. This insurance covers risks associated with construction projects, including damage to property, improper construction, renovation-related damages, and injuries to workers or subcontractors. It provides comprehensive coverage, bridging the gaps between different types of risks that contractors face.',
      'img' => '05_Contractors_All_Risks_Insurance.png',
    ],
    6 => [
      'name' => 'Crop Insurance',
      'short' => 'Protection for farmers against weather, pests, and disease losses.',
      'desc' => 'Royal Associates offers Crop Insurance to protect farmers and agricultural businesses against financial losses caused by adverse weather conditions, natural disasters, pests, and diseases. This insurance provides coverage for the loss of crops or crop revenue, ensuring that farmers can recover financially and sustain their operations in the face of unpredictable events. It offers protection against risks beyond farmers\' control, helping to stabilize their income and protect their livelihoods.',
      'img' => '06_Crop_Insurance.png',
    ],
    7 => [
      'name' => 'Livestock Insurance',
      'short' => 'Coverage for livestock owners against death or injury of animals.',
      'desc' => 'Livestock Insurance provided by Royal Associates offers coverage for farmers and livestock owners against losses due to the death or injury of their animals. This insurance protects against risks such as accidents, acts of God, theft, and other unforeseen events. It provides financial compensation for the value of lost livestock, helping farmers recover and continue their livestock operations.',
      'img' => '07_Livestock_Insurance.png',
    ],
    8 => [
      'name' => 'Risk Management Services',
      'short' => 'Services to identify, assess, and mitigate project and business risks.',
      'desc' => 'Royal Associates specializes in Risk Management Services, helping organizations improve their project management practices, governance, and decision-making processes. Their services focus on identifying, assessing, and mitigating risks at every stage of a project or business operation. By analyzing an organization\'s risk management maturity, processes, methodologies, and culture, Royal Associates helps develop effective risk management strategies to minimize potential losses and maximize returns on investment.',
      'img' => '08_Risk_Management_Services.png',
    ],
    9 => [
      'name' => 'Directors and Officers Liability',
      'short' => 'Protection for directors and officers against personal liability claims.',
      'desc' => 'Directors and Officers (D&O) Liability Insurance offered by Royal Associates protects corporate directors and officers, as well as their spouses, from personal liability in the event they are sued for alleged wrongful acts in managing a company. This insurance covers legal defense costs, settlements, and damages arising from lawsuits brought by employees, vendors, competitors, investors, customers, or other parties. It safeguards the personal assets of directors and officers, providing financial security and peace of mind.',
      'img' => '09_Directors_and_Officers_Liability.png',
    ],
    10 => [
      'name' => 'Group Personal Accident',
      'short' => 'Compensation for employees for accidental bodily injuries.',
      'desc' => 'Royal Associates provides Group Personal Accident Insurance, which offers compensation to employees for bodily injuries resulting from accidents. This insurance covers accidental, violent, visible, and external injuries that lead to death or disablement. It ensures that employees receive financial support in the event of an accident, helping them cope with medical expenses, loss of income, and other related costs.',
      'img' => '10_Group_Personal_Accident.png',
    ],
    11 => [
      'name' => 'Manufacturing Risks Insurance',
      'short' => 'Tailored coverage for manufacturing operations and equipment.',
      'desc' => 'Manufacturing Risks Insurance is a tailored policy offered by Royal Associates specifically designed for manufacturing operations. This insurance covers various risks associated with manufacturing, including service interruptions, product recalls, equipment breakdowns, and worker injuries. It helps manufacturing businesses mitigate financial losses and protect their assets, ensuring continuity of operations and minimizing disruptions.',
      'img' => '11_Manufacturing_Risks_Insurance.png',
    ],
    12 => [
      'name' => 'Medical Malpractice Insurance',
      'short' => 'Liability coverage for healthcare professionals against claims.',
      'desc' => 'Royal Associates provides Medical Malpractice Insurance, which offers liability coverage for healthcare professionals against claims arising from disputed medical services resulting in patient injury or death. This insurance covers legal expenses, settlement costs, compensatory and punitive damages, and medical damages. Medical Malpractice Insurance helps protect healthcare professionals\' reputations, assets, and professional careers.',
      'img' => '12_Medical_Malpractice_Insurance.png',
    ],
    14 => [
      'name' => 'Professional Indemnity',
      'short' => 'Protection for professionals against negligence and error claims.',
      'desc' => 'Professional Indemnity Insurance protects professionals, such as consultants, architects, engineers, and lawyers, from the cost of defending against claims brought by clients for alleged negligence, errors, or omissions in their professional services. Royal Associates offers this insurance, which covers legal expenses, settlements, and damages awarded in civil lawsuits. It helps professionals safeguard their reputations, assets, and professional practices.',
      'img' => '14_Professional_Indemnity.png',
    ],
    16 => [
      'name' => 'Trade Credit Insurance',
      'short' => 'Protection against non-payment of commercial trade debts.',
      'desc' => 'Trade Credit Insurance offered by Royal Associates protects manufacturers, traders, and service providers against losses arising from non-payment or late payment of commercial trade debts. This insurance provides coverage if a buyer fails to pay or pays late due to insolvency, bankruptcy, protracted default, or other specified events. It helps businesses manage credit risks, safeguard their cash flow, and maintain financial stability.',
      'img' => '16_Trade_Credit_Insurance.png',
    ],
    19 => [
      'name' => 'Office Insurance',
      'short' => 'Coverage for office spaces, furniture, equipment, and stock.',
      'desc' => 'Office Insurance offered by Royal Associates provides coverage for office spaces and their contents, including furniture, equipment, fixtures, and stock. This insurance protects businesses from risks such as fire, theft, natural disasters, and other specified events that could cause damage or loss. It helps businesses recover financially and resume operations swiftly after an unforeseen event.',
      'img' => '19_Office_Insurance.png',
    ],
    20 => [
      'name' => 'Work Injury Benefits (WIBA) and Hybrid WIBA',
      'short' => 'Coverage for employees\' work-related injuries or occupational diseases.',
      'desc' => 'Royal Associates offers Work Injury Benefits (WIBA) and Hybrid WIBA, which provide coverage for employees\' work-related injuries or occupational diseases. This insurance covers medical expenses, disability benefits, and death benefits in the event of a work-related accident or illness. It ensures that employees receive financial support and appropriate compensation for work-related injuries or illnesses.',
      'img' => '20_Work_Injury_Benefits_WIBA_and_Hybrid_WIBA.png',
    ],
    21 => [
      'name' => 'Oil & Gas Insurance',
      'short' => 'Coverage for oil and gas industry risks and operations.',
      'desc' => 'Oil & Gas Insurance provided by Royal Associates is specifically designed for companies operating in the oil and gas industry. This insurance covers various risks, including property damage, equipment breakdowns, business interruption, pollution liability, and employee injuries. It helps protect oil and gas companies from significant financial losses and ensures the continuity of their operations.',
      'img' => '21_Oil_and_Gas_Insurance.png',
    ],
    22 => [
      'name' => 'Property Insurance',
      'short' => 'Coverage for commercial and residential properties against damage.',
      'desc' => 'Property Insurance offered by Royal Associates provides coverage for commercial and residential properties against risks such as fire, theft, vandalism, natural disasters, and other specified events. This insurance protects property owners by covering the costs of repairs, replacements, and liability claims resulting from covered incidents.',
      'img' => '22_Property_Insurance.png',
    ],
    23 => [
      'name' => 'Liability Insurance',
      'short' => 'Protection against third-party claims for injury or property damage.',
      'desc' => 'Liability Insurance provided by Royal Associates offers protection against legal liabilities arising from third-party claims for bodily injury, property damage, or personal injury. This insurance covers legal defense costs, settlements, and judgments awarded to claimants. It helps businesses and individuals mitigate the financial risks associated with potential liability claims.',
      'img' => '23_Liability_Insurance.png',
    ],
    24 => [
      'name' => 'Cyber Risks Insurance',
      'short' => 'Coverage for losses from cyber attacks, data breaches, and incidents.',
      'desc' => 'Cyber Risks Insurance offered by Royal Associates provides coverage for losses and liabilities resulting from cyber attacks, data breaches, and other cyber incidents. This insurance helps businesses recover from the financial and reputational damages caused by cyber threats. It covers costs associated with data recovery, legal liabilities, customer notification, public relations, and regulatory compliance.',
      'img' => '24_Cyber_Risks_Insurance.png',
    ],
    25 => [
      'name' => 'Bonds and Guarantees',
      'short' => 'Financial instruments assuring contractual obligation fulfillment.',
      'desc' => 'Royal Associates offers Bonds and Guarantees, which are financial instruments that provide assurance to one party (the obligee) that another party (the principal) will fulfill their obligations under a contract. These bonds and guarantees can include performance bonds, bid bonds, advance payment guarantees, and other types of surety bonds. They help businesses build trust, secure contracts, and ensure contractual obligations are met.',
      'img' => '25_Bonds_and_Guarantees.png',
    ],
    26 => [
      'name' => 'Marine Insurance',
      'short' => 'Coverage for marine vessels, cargo, and maritime operations.',
      'desc' => 'Marine Insurance provided by Royal Associates covers risks associated with marine vessels, cargo transportation, and marine-related operations. This insurance includes coverage for hull and machinery, cargo damage or loss, liability, and other risks specific to marine activities. It safeguards marine businesses and individuals from financial losses and liabilities that may arise during maritime operations.',
      'img' => '26_Marine_Insurance.png',
    ],
    27 => [
      'name' => 'Aviation Insurance',
      'short' => 'Coverage for aircraft owners, operators, and aviation businesses.',
      'desc' => 'Aviation Insurance offered by Royal Associates provides coverage for aircraft owners, operators, and aviation-related businesses. This insurance protects against risks such as aircraft damage, third-party liability, bodily injury, property damage, and hull losses. It ensures that aviation professionals and organizations have the necessary coverage to operate safely and protect their assets.',
      'img' => '27_Aviation_Insurance.png',
    ],
    28 => [
      'name' => 'Asset Insurance',
      'short' => 'Coverage for equipment, machinery, inventory, and valuable property.',
      'desc' => 'Asset Insurance provided by Royal Associates covers various types of assets, including equipment, machinery, inventory, and other valuable property. This insurance protects against risks such as damage, theft, fire, and natural disasters. It helps businesses safeguard their assets and recover financially in the event of unexpected losses or damages.',
      'img' => '28_Asset_Insurance.png',
    ],
    31 => [
      'name' => 'Environmental Impact Insurance',
      'short' => 'Coverage for environmental risks and liabilities from operations.',
      'desc' => 'Environmental Impact Insurance offered by Royal Associates provides coverage for environmental risks and liabilities associated with industrial activities, construction projects, and other operations that may impact the environment. This insurance covers costs related to pollution cleanup, legal liabilities, and damage to natural resources. It helps businesses mitigate the financial and reputational risks associated with environmental incidents.',
      'img' => '31_Environmental_Impact_Insurance.png',
    ],
    32 => [
      'name' => 'Premium Finance Services',
      'short' => 'Financing options to pay insurance premiums in installments.',
      'desc' => 'Premium Finance Services provided by Royal Associates assist clients in managing their insurance premiums by offering financing options. This service allows policyholders to pay their insurance premiums in installments rather than a lump sum, providing greater flexibility in managing cash flow. Premium Finance Services help individuals and businesses ensure their insurance coverage remains active and uninterrupted.',
      'img' => '32_Premium_Finance_Services.png',
    ],
  ],
  'all_ordered' => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
];
